import random

NEGATION_TABLE = "p  | p'\nV  | F\nF  | V"
CONJUNCTION_TABLE = "p  | q  | p•q\nV  | V  | V\nV  | F  | F\nF  | V  | F\nF  | F  | F"
DISJUNCTION_TABLE = "p  | q  | p+q\nV  | V  | V\nV  | F  | V\nF  | V  | V\nF  | F  | F"
CONDITIONAL_TABLE = "p  | q  | p→q\nV  | V  | V\nV  | F  | F\nF  | V  | V\nF  | F  | V"
BICONDITIONAL_TABLE = "p  | q  | p↔q\nV  | V  | V\nV  | F  | F\nF  | V  | F\nF  | F  | V"
MP_RULE = "Modus Ponens (MP):\np → q\np\n∴ q"
MT_RULE = "Modus Tollens (MT):\np → q\nq'\n∴ p'"
SH_RULE = "Silogismo Hipotético (SH):\np → q\nq → r\n∴ p → r"
SD_RULE = "Silogismo Disjuntivo (SD):\np + q\np'\n∴ q"
DC_RULE = "Dilema Construtivo (DC):\np → q, r → s\np + r\n∴ q + s"
DD_RULE = "Dilema Destrutivo (DD):\np → q, r → s\nq' + s'\n∴ p' + r'"

QUESTIONS: list[dict] = [
    # ── EASY (20) ────────────────────────────────────────────────────
    {
        "id": "easy_01",
        "topic": "proposicoes",
        "subtopic": "identificar_proposicao",
        "difficulty": "easy",
        "question": "Qual das seguintes sentenças É uma proposição?",
        "options": ["A) Estude mais!", "B) Como vai você?", "C) O Brasil fica na América do Sul.", "D) Feche a porta."],
        "correct": "C",
        "explanation": "Proposição é sentença declarativa com valor verdade definido. 'O Brasil fica na América do Sul' é declarativa e verdadeira. As demais são imperativa, interrogativa e imperativa.",
        "help_table": "Proposição: sentença declarativa que é V ou F.\nNÃO são proposições: exclamativas, interrogativas, imperativas.",
    },
    {
        "id": "easy_02",
        "topic": "proposicoes",
        "subtopic": "identificar_proposicao",
        "difficulty": "easy",
        "question": "Qual das seguintes NÃO é uma proposição?",
        "options": ["A) 5 < 2", "B) A Alemanha fica na Ásia.", "C) Como é o seu nome?", "D) Todo cachorro é mamífero."],
        "correct": "C",
        "explanation": "'Como é o seu nome?' é interrogativa — não pode ser V nem F. As demais são proposições (falsas ou verdadeiras).",
        "help_table": "Proposição: sentença declarativa que é V ou F.\nNÃO são proposições: exclamativas, interrogativas, imperativas.",
    },
    {
        "id": "easy_03",
        "topic": "proposicoes",
        "subtopic": "identificar_proposicao",
        "difficulty": "easy",
        "question": "'Vamos trabalhar!' — Do ponto de vista da lógica, essa sentença é:",
        "options": ["A) Proposição verdadeira", "B) Proposição falsa", "C) Não é proposição — é imperativa", "D) Proposição composta"],
        "correct": "C",
        "explanation": "Sentenças imperativas não são proposições pois não têm valor lógico definido (V ou F).",
        "help_table": "Proposição: sentença declarativa que é V ou F.\nNÃO são proposições: exclamativas, interrogativas, imperativas.",
    },
    {
        "id": "easy_04",
        "topic": "proposicoes",
        "subtopic": "identificar_proposicao",
        "difficulty": "easy",
        "question": "'x + 5 = 0' — Do ponto de vista da lógica, essa sentença é:",
        "options": ["A) Proposição verdadeira", "B) Proposição falsa", "C) Sentença aberta — não é proposição", "D) Proposição composta"],
        "correct": "C",
        "explanation": "'x + 5 = 0' contém variável livre x — seu valor lógico depende de x, logo não é proposição (é sentença aberta).",
        "help_table": "Proposição: sentença declarativa que é V ou F.\nSentença aberta: contém variável, valor lógico indefinido.",
    },
    {
        "id": "easy_05",
        "topic": "proposicoes",
        "subtopic": "identificar_proposicao",
        "difficulty": "easy",
        "question": "Considere: I) 'Eu fui a São Paulo ontem.' II) 'Vamos trabalhar!' III) 'O número -2 é natural.' Quais SÃO proposições?",
        "options": ["A) Apenas I", "B) Apenas III", "C) I e III", "D) I, II e III"],
        "correct": "C",
        "explanation": "I é proposição (declarativa, valor pode ser determinado). II é imperativa (não é proposição). III é proposição falsa (-2 não é natural).",
        "help_table": "Proposição: sentença declarativa que é V ou F.\nNÃO são proposições: exclamativas, interrogativas, imperativas.",
    },
    {
        "id": "easy_06",
        "topic": "proposicoes",
        "subtopic": "valor_logico",
        "difficulty": "easy",
        "question": "Qual o valor lógico de p: '2 + 2 = 4'?",
        "options": ["A) Falso", "B) Verdadeiro", "C) Indeterminado", "D) Nulo"],
        "correct": "B",
        "explanation": "2 + 2 = 4 é uma igualdade matemática verdadeira, portanto V(p) = 1 (Verdadeiro).",
        "help_table": "Valor lógico V(p) = 1 se p verdadeira, V(p) = 0 se p falsa.",
    },
    {
        "id": "easy_07",
        "topic": "proposicoes",
        "subtopic": "valor_logico",
        "difficulty": "easy",
        "question": "Qual o valor lógico de p: '5 < 2'?",
        "options": ["A) Verdadeiro", "B) Falso", "C) Indeterminado", "D) Depende de 5 e 2"],
        "correct": "B",
        "explanation": "5 < 2 é falso (5 é maior que 2), portanto V(p) = 0 (Falso).",
        "help_table": "Valor lógico V(p) = 1 se p verdadeira, V(p) = 0 se p falsa.",
    },
    {
        "id": "easy_08",
        "topic": "proposicoes",
        "subtopic": "valor_logico",
        "difficulty": "easy",
        "question": "Qual o valor lógico de: 'A Alemanha fica na Ásia'?",
        "options": ["A) Verdadeiro", "B) Falso", "C) Indeterminado", "D) Nulo"],
        "correct": "B",
        "explanation": "A Alemanha fica na Europa, não na Ásia. Portanto a proposição é Falsa.",
        "help_table": "Valor lógico V(p) = 1 se p verdadeira, V(p) = 0 se p falsa.",
    },
    {
        "id": "easy_09",
        "topic": "proposicoes",
        "subtopic": "valor_logico",
        "difficulty": "easy",
        "question": "Qual o valor lógico de: 'O número -2 é um número natural'?",
        "options": ["A) Verdadeiro", "B) Falso", "C) Indeterminado", "D) Nulo"],
        "correct": "B",
        "explanation": "Números naturais são N = {0, 1, 2, 3, ...}. -2 é negativo, portanto não é natural. Proposição Falsa.",
        "help_table": "Valor lógico V(p) = 1 se p verdadeira, V(p) = 0 se p falsa.",
    },
    {
        "id": "easy_10",
        "topic": "proposicoes",
        "subtopic": "valor_logico",
        "difficulty": "easy",
        "question": "Qual o valor lógico de: '1 + 4 ≠ 5'?",
        "options": ["A) Verdadeiro", "B) Falso", "C) Indeterminado", "D) Nulo"],
        "correct": "B",
        "explanation": "1 + 4 = 5, portanto 1 + 4 ≠ 5 é Falso.",
        "help_table": "Valor lógico V(p) = 1 se p verdadeira, V(p) = 0 se p falsa.",
    },
    {
        "id": "easy_11",
        "topic": "proposicoes",
        "subtopic": "negacao",
        "difficulty": "easy",
        "question": "Dada p: 'Está chovendo.' (Verdadeira). Qual o valor de p' (negação de p)?",
        "options": ["A) Verdadeiro", "B) Falso", "C) Indeterminado", "D) Depende do contexto"],
        "correct": "B",
        "explanation": "A negação inverte o valor lógico. p=V → p'=F.",
        "help_table": NEGATION_TABLE,
    },
    {
        "id": "easy_12",
        "topic": "proposicoes",
        "subtopic": "negacao",
        "difficulty": "easy",
        "question": "Dada q: 'Hoje não é domingo.' (Falsa). Qual o valor de q'?",
        "options": ["A) Falso", "B) Verdadeiro", "C) Nulo", "D) Indeterminado"],
        "correct": "B",
        "explanation": "q=F → q'=V. A negação de uma proposição falsa é verdadeira.",
        "help_table": NEGATION_TABLE,
    },
    {
        "id": "easy_13",
        "topic": "proposicoes",
        "subtopic": "negacao",
        "difficulty": "easy",
        "question": "Dada p: 'O Brasil fica na América do Sul.' (Verdadeira). Qual o valor de p'?",
        "options": ["A) Verdadeiro", "B) Falso", "C) Nulo", "D) Indeterminado"],
        "correct": "B",
        "explanation": "p=V → p'=F. A negação de uma proposição verdadeira é falsa.",
        "help_table": NEGATION_TABLE,
    },
    {
        "id": "easy_14",
        "topic": "proposicoes",
        "subtopic": "negacao",
        "difficulty": "easy",
        "question": "Se V(p) = 1, qual o valor de V(p')?",
        "options": ["A) 1 (Verdadeiro)", "B) 0 (Falso)", "C) Depende de p", "D) Indeterminado"],
        "correct": "B",
        "explanation": "Pela tabela da negação: V(p)=1 → V(p')=0.",
        "help_table": NEGATION_TABLE,
    },
    {
        "id": "easy_15",
        "topic": "proposicoes",
        "subtopic": "negacao",
        "difficulty": "easy",
        "question": "Se V(p) = 0, qual o valor de V(p')?",
        "options": ["A) 0 (Falso)", "B) 1 (Verdadeiro)", "C) Depende de p", "D) Nulo"],
        "correct": "B",
        "explanation": "Pela tabela da negação: V(p)=0 → V(p')=1.",
        "help_table": NEGATION_TABLE,
    },
    {
        "id": "easy_16",
        "topic": "proposicoes",
        "subtopic": "principios",
        "difficulty": "easy",
        "question": "Qual princípio afirma que uma proposição só pode ser verdadeira OU falsa, nunca outro valor?",
        "options": ["A) Princípio da não contradição", "B) Princípio do terceiro excluído", "C) Princípio da identidade", "D) Princípio da razão suficiente"],
        "correct": "B",
        "explanation": "O Princípio do Terceiro Excluído afirma que toda proposição tem exatamente dois valores possíveis: V ou F.",
        "help_table": "Princípio do Terceiro Excluído: toda proposição é V ou F — sem terceira opção.\nPrincípio da Não Contradição: uma proposição não pode ser V e F simultaneamente.",
    },
    {
        "id": "easy_17",
        "topic": "proposicoes",
        "subtopic": "tabela_verdade_basica",
        "difficulty": "easy",
        "question": "Quantas linhas tem uma tabela-verdade com 2 proposições (p e q)?",
        "options": ["A) 2", "B) 3", "C) 4", "D) 8"],
        "correct": "C",
        "explanation": "Número de linhas = 2^n onde n é o número de proposições. 2^2 = 4 linhas.",
        "help_table": "Fórmula: 2^n linhas para n proposições.\n2^1=2, 2^2=4, 2^3=8, 2^4=16",
    },
    {
        "id": "easy_18",
        "topic": "proposicoes",
        "subtopic": "tabela_verdade_basica",
        "difficulty": "easy",
        "question": "Quantas linhas tem uma tabela-verdade com 3 proposições (p, q e r)?",
        "options": ["A) 3", "B) 4", "C) 6", "D) 8"],
        "correct": "D",
        "explanation": "Número de linhas = 2^n = 2^3 = 8 linhas.",
        "help_table": "Fórmula: 2^n linhas para n proposições.\n2^1=2, 2^2=4, 2^3=8, 2^4=16",
    },
    {
        "id": "easy_19",
        "topic": "proposicoes",
        "subtopic": "identificar_proposicao",
        "difficulty": "easy",
        "question": "'Quem comprou o pastel?' — Do ponto de vista da lógica, essa sentença é:",
        "options": ["A) Proposição verdadeira", "B) Proposição falsa", "C) Não é proposição — é interrogativa", "D) Proposição composta"],
        "correct": "C",
        "explanation": "Sentenças interrogativas não são proposições pois não têm valor lógico definido.",
        "help_table": "Proposição: sentença declarativa que é V ou F.\nNÃO são proposições: exclamativas, interrogativas, imperativas.",
    },
    {
        "id": "easy_20",
        "topic": "proposicoes",
        "subtopic": "negacao",
        "difficulty": "easy",
        "question": "A negação de 'Está chovendo' é:",
        "options": ["A) Está muito chovendo", "B) Não está chovendo", "C) Talvez esteja chovendo", "D) Vai chover"],
        "correct": "B",
        "explanation": "A negação (¬p ou p') de 'Está chovendo' é 'Não está chovendo'.",
        "help_table": NEGATION_TABLE,
    },

    # ── MEDIUM (20) ───────────────────────────────────────────────────
    {
        "id": "med_01",
        "topic": "proposicoes",
        "subtopic": "conjuncao",
        "difficulty": "medium",
        "question": "A conjunção p • q é verdadeira quando:",
        "options": ["A) Pelo menos uma for verdadeira", "B) Ambas forem verdadeiras", "C) Pelo menos uma for falsa", "D) Ambas forem falsas"],
        "correct": "B",
        "explanation": "Conjunção (e): p • q é V somente quando AMBAS p e q são verdadeiras.",
        "help_table": CONJUNCTION_TABLE,
    },
    {
        "id": "med_02",
        "topic": "proposicoes",
        "subtopic": "conjuncao",
        "difficulty": "medium",
        "question": "Dadas p: 'Maria é bonita' (V) e q: 'Maria é elegante' (V). Qual o valor de p • q?",
        "options": ["A) Falso", "B) Verdadeiro", "C) Indeterminado", "D) Depende"],
        "correct": "B",
        "explanation": "p=V, q=V → p•q=V. Conjunção é V quando ambas são V.",
        "help_table": CONJUNCTION_TABLE,
    },
    {
        "id": "med_03",
        "topic": "proposicoes",
        "subtopic": "conjuncao",
        "difficulty": "medium",
        "question": "Se V(p) = 1 e V(q) = 0, qual o valor de p • q?",
        "options": ["A) Verdadeiro", "B) Falso", "C) Indeterminado", "D) Nulo"],
        "correct": "B",
        "explanation": "p=V, q=F → p•q=F. Conjunção é falsa quando ao menos uma for falsa.",
        "help_table": CONJUNCTION_TABLE,
    },
    {
        "id": "med_04",
        "topic": "proposicoes",
        "subtopic": "conjuncao",
        "difficulty": "medium",
        "question": "Se V(p) = 1 e V(q) = 0, qual o valor de p • q'?",
        "options": ["A) Verdadeiro", "B) Falso", "C) Indeterminado", "D) Nulo"],
        "correct": "A",
        "explanation": "q'=V (negação de F). p•q' = V•V = V.",
        "help_table": CONJUNCTION_TABLE,
    },
    {
        "id": "med_05",
        "topic": "proposicoes",
        "subtopic": "conjuncao",
        "difficulty": "medium",
        "question": "Dado V(p) = 1. Qual o valor de p • p'?",
        "options": ["A) Verdadeiro", "B) Falso", "C) Indeterminado", "D) Depende de p"],
        "correct": "B",
        "explanation": "p'=F (negação de V). p•p' = V•F = F. Uma proposição e sua negação sempre têm conjunção falsa.",
        "help_table": CONJUNCTION_TABLE,
    },
    {
        "id": "med_06",
        "topic": "proposicoes",
        "subtopic": "disjuncao",
        "difficulty": "medium",
        "question": "A disjunção p + q é FALSA somente quando:",
        "options": ["A) Ambas forem verdadeiras", "B) p for V e q for F", "C) Ambas forem falsas", "D) p for F e q for V"],
        "correct": "C",
        "explanation": "Disjunção (ou): p + q é F somente quando AMBAS p e q são falsas.",
        "help_table": DISJUNCTION_TABLE,
    },
    {
        "id": "med_07",
        "topic": "proposicoes",
        "subtopic": "disjuncao",
        "difficulty": "medium",
        "question": "Dadas p (Verdadeira) e q (Falsa). Qual o valor de p + q?",
        "options": ["A) Falso", "B) Verdadeiro", "C) Indeterminado", "D) Nulo"],
        "correct": "B",
        "explanation": "p=V, q=F → p+q=V. Disjunção é V quando pelo menos uma é V.",
        "help_table": DISJUNCTION_TABLE,
    },
    {
        "id": "med_08",
        "topic": "proposicoes",
        "subtopic": "disjuncao",
        "difficulty": "medium",
        "question": "Se V(p) = 1 e V(q) = 0, qual o valor de p' + q'?",
        "options": ["A) Verdadeiro", "B) Falso", "C) Indeterminado", "D) Nulo"],
        "correct": "A",
        "explanation": "p'=F, q'=V. p'+q' = F+V = V.",
        "help_table": DISJUNCTION_TABLE,
    },
    {
        "id": "med_09",
        "topic": "proposicoes",
        "subtopic": "condicional",
        "difficulty": "medium",
        "question": "O condicional p → q é FALSO somente quando:",
        "options": ["A) p é F e q é F", "B) p é V e q é V", "C) p é V e q é F", "D) p é F e q é V"],
        "correct": "C",
        "explanation": "Condicional é F somente quando a hipótese (p) é V e a conclusão (q) é F.",
        "help_table": CONDITIONAL_TABLE,
    },
    {
        "id": "med_10",
        "topic": "proposicoes",
        "subtopic": "condicional",
        "difficulty": "medium",
        "question": "Dadas p: 'Chove' (V) e q: 'Faz sol' (F). Qual o valor de p → q?",
        "options": ["A) Verdadeiro", "B) Falso", "C) Indeterminado", "D) Depende"],
        "correct": "B",
        "explanation": "p=V, q=F → p→q=F. Condicional com hipótese V e conclusão F é sempre F.",
        "help_table": CONDITIONAL_TABLE,
    },
    {
        "id": "med_11",
        "topic": "proposicoes",
        "subtopic": "condicional",
        "difficulty": "medium",
        "question": "Se V(p) = 0 e V(q) = 0, qual o valor de p → q?",
        "options": ["A) Falso", "B) Verdadeiro", "C) Indeterminado", "D) Nulo"],
        "correct": "B",
        "explanation": "p=F, q=F → p→q=V. Condicional com hipótese F é sempre V.",
        "help_table": CONDITIONAL_TABLE,
    },
    {
        "id": "med_12",
        "topic": "proposicoes",
        "subtopic": "condicional",
        "difficulty": "medium",
        "question": "Dada: 'Se 5+5=9, então 6+6=12.' Qual o valor lógico?",
        "options": ["A) Falso", "B) Verdadeiro", "C) Indeterminado", "D) Nulo"],
        "correct": "B",
        "explanation": "p: '5+5=9' é F. Condicional com hipótese F é sempre V, independente de q.",
        "help_table": CONDITIONAL_TABLE,
    },
    {
        "id": "med_13",
        "topic": "proposicoes",
        "subtopic": "condicional",
        "difficulty": "medium",
        "question": "'Se eu sair de casa, vou ao cinema.' p='saí de casa'(V), q='vou ao cinema'(F). Valor da proposição?",
        "options": ["A) Verdadeiro", "B) Falso", "C) Indeterminado", "D) Nulo"],
        "correct": "B",
        "explanation": "p=V, q=F → p→q=F. A única situação que torna o condicional falso.",
        "help_table": CONDITIONAL_TABLE,
    },
    {
        "id": "med_14",
        "topic": "proposicoes",
        "subtopic": "bicondicional",
        "difficulty": "medium",
        "question": "O bicondicional p ↔ q é verdadeiro quando:",
        "options": ["A) p é V e q é F", "B) p e q têm valores lógicos iguais", "C) p é F e q é V", "D) Apenas quando ambas são V"],
        "correct": "B",
        "explanation": "Bicondicional é V quando p e q têm o MESMO valor lógico (ambas V ou ambas F).",
        "help_table": BICONDITIONAL_TABLE,
    },
    {
        "id": "med_15",
        "topic": "proposicoes",
        "subtopic": "bicondicional",
        "difficulty": "medium",
        "question": "Dadas p (F) e q (F). Qual o valor de p ↔ q?",
        "options": ["A) Falso", "B) Verdadeiro", "C) Indeterminado", "D) Nulo"],
        "correct": "B",
        "explanation": "p=F, q=F → valores iguais → p↔q=V.",
        "help_table": BICONDITIONAL_TABLE,
    },
    {
        "id": "med_16",
        "topic": "proposicoes",
        "subtopic": "bicondicional",
        "difficulty": "medium",
        "question": "Sendo V(p)=1 e V(q)=0. Qual o valor de p ↔ q?",
        "options": ["A) Verdadeiro", "B) Falso", "C) Indeterminado", "D) Nulo"],
        "correct": "B",
        "explanation": "p=V, q=F → valores diferentes → p↔q=F.",
        "help_table": BICONDITIONAL_TABLE,
    },
    {
        "id": "med_17",
        "topic": "proposicoes",
        "subtopic": "precedencia",
        "difficulty": "medium",
        "question": "Qual a ordem correta de precedência dos operadores lógicos (do maior para o menor)?",
        "options": ["A) →, ↔, ¬, ∧, ∨", "B) ¬, ∧ e ∨, →, ↔", "C) ∧ e ∨, ¬, →, ↔", "D) ↔, →, ∧ e ∨, ¬"],
        "correct": "B",
        "explanation": "Ordem: 1°) Negação (¬), 2°) Conjunção (∧) e Disjunção (∨), 3°) Condicional (→), 4°) Bicondicional (↔).",
        "help_table": "Ordem dos operadores:\n1) Negação (¬ / ')\n2) Conjunção (∧ / •) e Disjunção (∨ / +)\n3) Condicional (→)\n4) Bicondicional (↔)",
    },
    {
        "id": "med_18",
        "topic": "proposicoes",
        "subtopic": "condicional",
        "difficulty": "medium",
        "question": "Dada a proposição: 'Se 2 é par, então 3 é primo.' Qual seu valor lógico?",
        "options": ["A) Falso", "B) Verdadeiro", "C) Indeterminado", "D) Depende de 2"],
        "correct": "B",
        "explanation": "p: '2 é par' (V), q: '3 é primo' (V). p→q = V→V = V.",
        "help_table": CONDITIONAL_TABLE,
    },
    {
        "id": "med_19",
        "topic": "proposicoes",
        "subtopic": "conjuncao",
        "difficulty": "medium",
        "question": "Sejam p='Tavares é estudioso'(V) e q='Aranhas voam'(F). Qual o valor de p • q?",
        "options": ["A) Verdadeiro", "B) Falso", "C) Indeterminado", "D) Nulo"],
        "correct": "B",
        "explanation": "p=V, q=F → p•q=F. Conjunção com uma proposição falsa é sempre falsa.",
        "help_table": CONJUNCTION_TABLE,
    },
    {
        "id": "med_20",
        "topic": "proposicoes",
        "subtopic": "bicondicional",
        "difficulty": "medium",
        "question": "Dadas p (V) e q (V). Qual o valor de (p → q) ↔ (q → p)?",
        "options": ["A) Falso", "B) Verdadeiro", "C) Indeterminado", "D) Nulo"],
        "correct": "B",
        "explanation": "p→q = V→V = V. q→p = V→V = V. V↔V = V.",
        "help_table": BICONDITIONAL_TABLE,
    },

    # ── HARD (20) ────────────────────────────────────────────────────
    {
        "id": "hard_01",
        "topic": "argumentos",
        "subtopic": "argumento_valido",
        "difficulty": "hard",
        "question": "Um argumento é VÁLIDO quando:",
        "options": ["A) Todas as premissas são verdadeiras", "B) A conclusão é verdadeira", "C) Sempre que as premissas são V, a conclusão também é V", "D) A conclusão é falsa quando premissas são falsas"],
        "correct": "C",
        "explanation": "Argumento válido: sempre que todas as premissas forem V, a conclusão também será V. Validade é sobre a forma, não sobre valores concretos.",
        "help_table": "Argumento válido: p1•p2•...•pn → conclusão é tautologia.\nInválido: existe linha com todas premissas V e conclusão F.",
    },
    {
        "id": "hard_02",
        "topic": "argumentos",
        "subtopic": "argumento_valido",
        "difficulty": "hard",
        "question": "Um argumento é INVÁLIDO quando existe alguma linha da tabela-verdade onde:",
        "options": ["A) Todas as premissas são F e a conclusão é F", "B) Todas as premissas são V e a conclusão é F", "C) Todas as premissas são F e a conclusão é V", "D) Alguma premissa é V e a conclusão é V"],
        "correct": "B",
        "explanation": "Argumento inválido = existe ao menos uma linha onde TODAS as premissas são V e a conclusão é F (ocorre o par 1,0).",
        "help_table": "Argumento válido: não existe linha com premissas V e conclusão F.\nInválido: existe ao menos uma tal linha.",
    },
    {
        "id": "hard_03",
        "topic": "argumentos",
        "subtopic": "modus_ponens",
        "difficulty": "hard",
        "question": "O argumento Modus Ponens (MP) tem a forma:",
        "options": ["A) p→q, q' / p'", "B) p→q, p / q", "C) p→q, q / p", "D) p, q / p•q"],
        "correct": "B",
        "explanation": "Modus Ponens: de 'p→q' e 'p', concluímos 'q'. É a implicação (p→q)•p ⟹ q.",
        "help_table": MP_RULE,
    },
    {
        "id": "hard_04",
        "topic": "argumentos",
        "subtopic": "modus_tollens",
        "difficulty": "hard",
        "question": "O argumento Modus Tollens (MT) tem a forma:",
        "options": ["A) p→q, p / q", "B) p→q, q' / p'", "C) p→q, q / p", "D) p→q / p→(p•q)"],
        "correct": "B",
        "explanation": "Modus Tollens: de 'p→q' e 'q'' (negação da conclusão), concluímos 'p'' (negação da hipótese).",
        "help_table": MT_RULE,
    },
    {
        "id": "hard_05",
        "topic": "argumentos",
        "subtopic": "silogismo_hipotetico",
        "difficulty": "hard",
        "question": "Silogismo Hipotético (SH): das premissas p→q e q→r, concluímos:",
        "options": ["A) p→r", "B) p•r", "C) q→p", "D) r→p"],
        "correct": "A",
        "explanation": "Silogismo Hipotético: encadeia condicionais. De p→q e q→r, conclui p→r.",
        "help_table": SH_RULE,
    },
    {
        "id": "hard_06",
        "topic": "argumentos",
        "subtopic": "silogismo_disjuntivo",
        "difficulty": "hard",
        "question": "Silogismo Disjuntivo (SD): das premissas p+q e p', concluímos:",
        "options": ["A) p", "B) p'", "C) q", "D) q'"],
        "correct": "C",
        "explanation": "Silogismo Disjuntivo: de 'p+q' (pelo menos um é V) e 'p'' (p é F), concluímos que q deve ser V.",
        "help_table": SD_RULE,
    },
    {
        "id": "hard_07",
        "topic": "argumentos",
        "subtopic": "adicao",
        "difficulty": "hard",
        "question": "Pela regra de Adição (A): de p (verdadeiro), podemos concluir:",
        "options": ["A) p•q", "B) p+q", "C) p→q", "D) p↔q"],
        "correct": "B",
        "explanation": "Adição: de p verdadeiro, podemos adicionar qualquer q e a disjunção p+q será verdadeira.",
        "help_table": "Adição (A):\np\n∴ p + q",
    },
    {
        "id": "hard_08",
        "topic": "argumentos",
        "subtopic": "simplificacao",
        "difficulty": "hard",
        "question": "Pela regra de Simplificação (S): de p•q (conjunção), podemos concluir:",
        "options": ["A) p+q", "B) p→q", "C) p (ou q)", "D) p↔q"],
        "correct": "C",
        "explanation": "Simplificação: se p•q é V (ambas V), podemos extrair p (ou q) individualmente.",
        "help_table": "Simplificação (S):\np • q\n∴ p",
    },
    {
        "id": "hard_09",
        "topic": "argumentos",
        "subtopic": "dilema_construtivo",
        "difficulty": "hard",
        "question": "Dilema Construtivo (DC): das premissas p→q, r→s e p+r, concluímos:",
        "options": ["A) p•r", "B) q•s", "C) q+s", "D) p→s"],
        "correct": "C",
        "explanation": "Dilema Construtivo: se p leva a q, r leva a s, e ocorre p ou r, então ocorre q ou s.",
        "help_table": DC_RULE,
    },
    {
        "id": "hard_10",
        "topic": "argumentos",
        "subtopic": "dilema_destrutivo",
        "difficulty": "hard",
        "question": "Dilema Destrutivo (DD): das premissas p→q, r→s e q'+s', concluímos:",
        "options": ["A) p+r", "B) p•r", "C) p'+r'", "D) q+s"],
        "correct": "C",
        "explanation": "Dilema Destrutivo: se q' ou s' (negações das conclusões), então p' ou r' (negações das hipóteses).",
        "help_table": DD_RULE,
    },
    {
        "id": "hard_11",
        "topic": "argumentos",
        "subtopic": "dupla_negacao",
        "difficulty": "hard",
        "question": "Pela Dupla Negação (DN): de (p')' podemos concluir:",
        "options": ["A) p'", "B) p", "C) p→p'", "D) p•p'"],
        "correct": "B",
        "explanation": "Dupla Negação: negar duas vezes volta ao original. (p')' = p.",
        "help_table": "Dupla Negação (DN):\n(p')'\n∴ p\n\nou: p\n∴ (p')'",
    },
    {
        "id": "hard_12",
        "topic": "argumentos",
        "subtopic": "modus_ponens",
        "difficulty": "hard",
        "question": "Das premissas: 'Se João estudou, então João passou' e 'João estudou' (ambas V), concluímos:",
        "options": ["A) João não passou", "B) João passou na prova", "C) João não estudou", "D) Nada pode ser concluído"],
        "correct": "B",
        "explanation": "Modus Ponens: p→q e p (ambas V) → q. João passou.",
        "help_table": MP_RULE,
    },
    {
        "id": "hard_13",
        "topic": "argumentos",
        "subtopic": "modus_tollens",
        "difficulty": "hard",
        "question": "Das premissas: 'Se chove, a rua fica molhada' e 'A rua NÃO ficou molhada', concluímos:",
        "options": ["A) Choveu", "B) Não choveu", "C) A rua ficou seca", "D) Nada pode ser concluído"],
        "correct": "B",
        "explanation": "Modus Tollens: p→q e q' → p'. 'rua não molhada' = q', logo 'não choveu' = p'.",
        "help_table": MT_RULE,
    },
    {
        "id": "hard_14",
        "topic": "argumentos",
        "subtopic": "identificar_regra",
        "difficulty": "hard",
        "question": "O argumento: 'p→q' e 'p' logo 'q' — chama-se:",
        "options": ["A) Modus Tollens", "B) Silogismo Hipotético", "C) Modus Ponens", "D) Silogismo Disjuntivo"],
        "correct": "C",
        "explanation": "Forma p→q, p / q é exatamente o Modus Ponens.",
        "help_table": MP_RULE,
    },
    {
        "id": "hard_15",
        "topic": "argumentos",
        "subtopic": "identificar_regra",
        "difficulty": "hard",
        "question": "O argumento: 'p→q', 'q'' logo 'p'' — chama-se:",
        "options": ["A) Modus Ponens", "B) Modus Tollens", "C) Adição", "D) Simplificação"],
        "correct": "B",
        "explanation": "Forma p→q, q' / p' é o Modus Tollens.",
        "help_table": MT_RULE,
    },
    {
        "id": "hard_16",
        "topic": "argumentos",
        "subtopic": "silogismo_hipotetico",
        "difficulty": "hard",
        "question": "Das premissas p→q e q→r pelo Silogismo Hipotético concluímos p→r. Se p=V e r=V, a conclusão p→r é:",
        "options": ["A) Falsa", "B) Verdadeira", "C) Indeterminada", "D) Inválida"],
        "correct": "B",
        "explanation": "p→r com p=V e r=V → V→V = V.",
        "help_table": SH_RULE,
    },
    {
        "id": "hard_17",
        "topic": "argumentos",
        "subtopic": "absorcao",
        "difficulty": "hard",
        "question": "Regra da Absorção (RA): de p→q, podemos concluir:",
        "options": ["A) p→(p+q)", "B) p→(p•q)", "C) p•q", "D) p+q"],
        "correct": "B",
        "explanation": "Absorção: p→q ⟹ p→(p•q). Se p implica q, então p implica (p e q).",
        "help_table": "Absorção (RA):\np → q\n∴ p → (p • q)",
    },
    {
        "id": "hard_18",
        "topic": "argumentos",
        "subtopic": "simplificacao_disjuntiva",
        "difficulty": "hard",
        "question": "Simplificação Disjuntiva (S+): das premissas p+r e p+r', concluímos:",
        "options": ["A) p+r", "B) r", "C) p", "D) p•r"],
        "correct": "C",
        "explanation": "S+: de (p+r) e (p+r') podemos concluir p, pois p aparece em ambas e r/r' se cancelam.",
        "help_table": "Simplificação Disjuntiva (S+):\np + r\np + r'\n∴ p",
    },
    {
        "id": "hard_19",
        "topic": "argumentos",
        "subtopic": "identificar_regra",
        "difficulty": "hard",
        "question": "O argumento: 'p+q' e 'p'' logo 'q' — chama-se:",
        "options": ["A) Modus Ponens", "B) Modus Tollens", "C) Silogismo Disjuntivo", "D) Adição"],
        "correct": "C",
        "explanation": "Forma p+q, p' / q é o Silogismo Disjuntivo.",
        "help_table": SD_RULE,
    },
    {
        "id": "hard_20",
        "topic": "argumentos",
        "subtopic": "dilema_construtivo",
        "difficulty": "hard",
        "question": "Se temos 'p→q', 'r→s' e 'p+r', qual regra usamos e o que concluímos?",
        "options": ["A) Modus Ponens → q", "B) Dilema Construtivo → q+s", "C) Silogismo Hipotético → p→s", "D) Dilema Destrutivo → p'+r'"],
        "correct": "B",
        "explanation": "As três premissas correspondem ao Dilema Construtivo (DC), que conclui q+s.",
        "help_table": DC_RULE,
    },
]


def pick_question(difficulty: str, exclude_ids: set[str]) -> dict | None:
    pool = [q for q in QUESTIONS if q["difficulty"] == difficulty and q["id"] not in exclude_ids]
    if not pool:
        return None
    return random.choice(pool)
